### ISSUE TITLE
Support for ESP32DevKitV3

### ISSUE THREAD

**Issue by packetkiller** [iforce2d/inavFollowme#10]
Anyone interested in updating this code to support the ESP32 Dev Kit V3?  If so, I am happy to take on the project.  I am thinking this would give great options for offloading other capabilities from the Flight Controller by providing another way to provide UARTS and analog and digital pins that could then feed back to iNAV telemetry.  I already have the prototype development started.  If would like to see it start here, please let me know, else I will fork and go from there...
BTW, this is a great project.  Pat yourself on the back...good job.

**Comment by iforce2d** [comment]
These days I am only using Ardupilot, if I make any further 'follow me' stuff it will be based on that. Might be best to link to your work here, so that others interested can find it. Sorry for the slow reply.
