### ISSUE TITLE
error in the codes - FollowMeTag and FollowMeController

### ISSUE THREAD

**Issue by shreyash2422** [iforce2d/inavFollowme#2]
the FollowMeTag gives the following error - Arduino: 1.8.3 (Windows 10), Board: "Arduino/Genuino Uno"

c:\program files (x86)\arduino\hardware\tools\avr\bin\../lib/gcc/avr/4.9.2/../../../../avr/bin/ar.exe: unable to rename 'core\core.a'; reason: File exists

exit status 1
Error compiling for board Arduino/Genuino Uno.

and the FollowMeController gives the following error -
u8glib.h doesnt exist 

Also there are some  header files that you have included in your code but  have not provided the .h files for the same .

**Comment by iforce2d** [comment]
The 'file exists' error is not a problem with my code. There is a file on your system that your current user does not have write permissions for. Maybe you made the file as root and now you're a normal user?

u8glib is here: https://github.com/olikraus/u8glib

If you want some help with the other header files you'll have to tell us what they are....

**Comment by shreyash2422** [comment]
I am using and spracing f3 acro version , arduino pro mini is connected on i2c , but the arduino is doing nothing , can I modify ur code amd connect it to UART on the fc ?

**Comment by iforce2d** [comment]
The arduino should be connected to the flight controller via UART, not I2C. Please read the explanation a bit more carefully, eg:

"FollowMeController uses MSP (MultiWii Serial Protocol) to communicate with the Cleanflight iNav flight controller.
http://www.stefanocottafavi.com/msp-the-multiwii-serial-protocol
http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol"
