### ISSUE TITLE
Error Code when Compile and Upload

### ISSUE THREAD

**Issue by Cyber98** [iforce2d/inavFollowme#4]
Sorry for my Problem... can you help me buddy..

i got error on your code, when i compile.... 
this code FollowMeController

FollowMeController.ino:37:20: error: U8glib.h: No such file or directory
In file included from FollowMeController.ino:40:
/cleanflight.h: In function 'void geoConvertLocalToGeodetic(gpsOrigin_s*, t_fp_vector*, gpsLocation_t*)':
cleanflight.h:125: error: 'lrintf' was not declared in this scope
In file included from FollowMeController.ino:41:
/nRF24.h: At global scope:
nRF24.h:3: error: 'RF24' does not name a type
/nRF24.h: In function 'void radio_setup()':
nRF24.h:47: error: 'radio' was not declared in this scope
nRF24.h:48: error: 'RF24_250KBPS' was not declared in this scope
/nRF24.h: In function 'void radio_loop()':
nRF24.h:57: error: 'radio' was not declared in this scope
In file included from FollowMeController.ino:44:
/msp.h: In function 'void msp_loop()':
msp.h:246: error: 'fabsf' was not declared in this scope
msp.h:307: error: 'sqrtf' was not declared in this scope
msp.h:339: error: 'sqrtf' was not declared in this scope
In file included from FollowMeController.ino:45:
/screen.h: At global scope:
screen.h:2: error: 'U8GLIB_SSD1306_128X64' does not name a type
/screen.h: In function 'void draw()':
screen.h:12: error: 'u8g' was not declared in this scope
/screen.h: In function 'void screen_setup()':
screen.h:22: error: 'u8g' was not declared in this scope
screen.h:23: error: 'u8g_font_fur11' was not declared in this scope
/screen.h: In function 'void screen_loop()':
screen.h:54: error: 'u8g' was not declared in this scope

and this Code FollowMeTag

In file included from FollowMeTag.ino:41:
/MS5611.h: In function 'int32_t baroCalculateAltitude()':
MS5611.h:368: error: 'powf' was not declared in this scope
MS5611.h:368: error: 'lrintf' was not declared in this scope
/MS5611.h: In function 'void performBaroCalibrationCycle()':
MS5611.h:379: error: 'powf' was not declared in this scope
In file included from FollowMeTag.ino:42:
/nRF24.h: At global scope:
nRF24.h:20: error: 'RF24' does not name a type
/nRF24.h: In function 'void radio_setup()':
nRF24.h:25: error: 'radio' was not declared in this scope
nRF24.h:27: error: 'RF24_250KBPS' was not declared in this scope
/nRF24.h: In function 'void radio_loop()':
nRF24.h:34: error: 'radio' was not declared in this scope

Please help me...!!!

**Comment by iforce2d** [comment]
I think you can find most of these answers very easily with google:
https://github.com/olikraus/u8glib
https://arduino-info.wikispaces.com/Nrf24L01-2.4GHz-HowTo
https://stackoverflow.com/questions/15965025/arduino-error-abs-was-not-declared-in-this-scope

This is a very complex project. To be honest if you are getting stuck at this point with the fundamentals, you should think about trying a simpler project first.

**Comment by Cyber98** [comment]
Yeeeah..  thanks for your answer...

But, i have  once problome again.... 

FollowMeController.ino:40:
/cleanflight.h: In function 'void geoConvertLocalToGeodetic(gpsOrigin_s*, t_fp_vector*, gpsLocation_t*)':
cleanflight.h:125: error: 'lrintf' was not declared in this scope

**Comment by Cyber98** [comment]
Where i must be insert code

#if ARDUINO >= 100
  #include "Arduino.h"
#else
  #include "WProgram.h"
#endif
  

https://stackoverflow.com/questions/15965025/arduino-error-abs-was-not-declared-in-this-scope

**Comment by iforce2d** [comment]
I think if you need to ask that question, you should not be attempting this project.

**Comment by Cyber98** [comment]
Hmmm... thanks buddy... but, i'm never stop learning for this project...

finally the code problem can be solved 😆😆😆
