### ISSUE TITLE
 No response from FollowMeCheker and Follow Me Controller

### ISSUE THREAD

**Issue by CyberTramp98** [iforce2d/inavFollowme#6]
Haiii Buddy....
i have problem ... 

sorry if my english is very bad

FollowMeCheker and FollowMeControllor do not respond to anything, the value in oled still shows the number zero ...

in this project, I use:
FollowMeTag
-Arduino Uno
-Nrf24l01 PA LNA
-Baro MS5611
-GPS Ublox M8n

FollowMeCheker
-Arduino Uno
-Nrf24l01 PA LNA
-Oled Display

FollowMeController
-Arduino Uno
-Narf24l01 PA LNA
-Oled Display

Quad
-Naze32 with Inav 1.7.3
-gps ublox m8n
but do not use gimbal

FollowMeCheker connects with quad via port UART1 with Baudrate MSP 115200

but still does not show any changes on the oled screen, the value remains zero ..
on the FollowMeControll, screen displaying RC: 10, and others remain zero ...

for each cable connection, I follow the information in the source code

Can you explain a little solution about the problem I faced ...?

one more, can i use flight controller Omnibus F4 pro in my quad for this project ...?

please help me ....!
thanks buddy

**Comment by iforce2d** [comment]
If you did everything the same as me and got a different result, I don't know how I could offer any solution. I have never used an Omnibus F4 but as long as there is a UART that you can set to the correct speed and MSP then it should be ok.

**Comment by CyberTramp98** [comment]
hmmm .... ok, some more questions, does the working voltage of nrf24l01 affect the communication between FollowMeController with Flight Controller ?, Because I use 3.3v output from arduino, and plus elco 10uF is connected between 3.3v with GND

**Comment by iforce2d** [comment]
nRF24l01 signal pins can handle 5v. But VCC must be powered with no more than 3.6v (preferably 3.0v if you are using 5v signals). If you have not used these radio modules before you might like to start with something simpler - this project is not very easy. You can find lots of good info about the nRF24 here: https://arduino-info.wikispaces.com/Nrf24L01-2.4GHz-HowTo

**Comment by Cyber98** [comment]
I tried using this promini 5V, and the nrf24 pcb antenna using base module as a voltage down to 3.3 v for FollowMeController .... i still connect with FC naze32di port UART1 with MSP and baud rate 115200, there is a slight change on the oled screen, pps shows the value of 10-30 and the right yaw shows the value 90 unchanged, but the RC shows the value 10 and does not change .... in your video it shows that the value position yaw on the left side of the screen from FC, in my case the yaw value of the right shows 90, and the left yaw remains zero, while the Tag is off .. the led indicator on pin 2 blinks slowly ... does the pps in followmecontroller come from FC or tag? sorry if confusing buddy .... one more..in your video show about followmecheker, is it using voltage dropdown also for its nrf ?, or directly connected to battery 3.7v? ....

**Comment by CyberTramp98** [comment]
I tried using this promini 5V, and the nrf24 pcb antenna using base module as a voltage down to 3.3 v for FollowMeController .... i still connect with FC naze32di port UART1 with MSP and baud rate 115200, there is a slight change on the oled screen, pps shows the value of 10-30 and the right yaw shows the value 90 unchanged, but the RC shows the value 10 and does not change .... in your video it shows that the value position yaw on the left side of the screen from FC, in my case the yaw value of the right shows 90, and the left yaw remains zero, while the Tag is off .. the led indicator on pin 2 blinks slowly ... does the pps in followmecontroller come from FC or tag? sorry if confusing buddy .... one more..in your video show about followmecheker, is it using voltage dropdown also for its nrf ?, or directly connected to battery 3.7v? ....

**Comment by CyberTramp98** [comment]
I have used this module on other project... the module works fine .... I tried again, using promini 5V, and nrf24 pcb antenna which uses base module as a voltage drop down to 3.3 v for FollowMeController .... i am still connect FollowMeController with FC naze32 on port UART1, with MSP and baud rate 115200, there is little change on oled screen, pps shows 10-30 value and yaw right shows 90 value unchanged, but RC still shows 10 and unchanged value, and value alt still zero .... in your video shows that the position of the left side value from the FC, in my case the yaw value of the right shows 90, and the left yaw remains zero, while the Tag is off .. the led indicator on pin 2 blinks slowly ... is the pps in the followmecontroller coming from FC or tags? sorry if confusing buddy .... 

one more..
in your video show about followmecheker, is it using voltage reducer also for its nrf ?, or directly connected to battery 3.7v?

**Comment by iforce2d** [comment]
Comment from Ben Parsonage on the video that might be relevant:
"I think I have found the problem. Basically iNav introduced what they call MSPv2 into iNav v1.73, which uses a slightly different structure for sent/received MSP messages. So pretty much if you try and use the Follow Me Controller with an FC running iNav v1.73 or higher you're not gonna get far."

**Comment by markgrecowork** [comment]
Chris so all along i have been struggling with this.

all i need to do is use a OLD inav release????

i will try this sunday

**Comment by CyberTramp98** [comment]
I have tried using inav 1.2 and 1.3, but the result is same, pps has value, while others are zero ... i do not know why

followmetag works if without baro, i give "//" to baro_setup () and baro_loop (now), oled in followmecheker shows pps: 56, lat: -677xxxxx, lon: 106xxxxx, alt: 0, (not using baro), and others also have value, ..... but if I use baro, I delete "//", followmetag does not send data, oled shows drops: 1, pps: 0, and others remain 0 ....

i tried the 30km testRange project, the tool worked well ... i think there is no problem with the nrf24 module ...

has anyone ever experienced the same thing?

anyone has any ideas? thanks
